# SPDX-License-Identifier: MIT
# Maul3D GDExtension build. Expects godot-cpp checked out as a
# sibling directory (see README) and the Maul3D static library
# built at ../../build/release.
import os

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/", "../../include/"])
env.Append(LIBPATH=["../../build/release/"])
env.Append(LIBS=["maul3d"])

sources = Glob("src/*.cpp")

lib_name = "bin/libmaul3d_godot{}{}".format(env["suffix"], env["SHLIBSUFFIX"])
if env["platform"] == "macos":
    lib_name = "bin/libmaul3d_godot.{}.{}.framework/libmaul3d_godot.{}.{}".format(
        env["platform"], env["target"], env["platform"], env["target"]
    )

library = env.SharedLibrary(lib_name, source=sources)
Default(library)
